### PR TITLE
Changed Picture Link to include the LA Rams

### PR DESCRIPTION
**Pull request by kaileu**

### CODE REVIEW

**Comment by Alexqw** [comment]
@kaileu Nice. Thanks!

Did you do any poking around when getting this new URL? I'm curious if you ran into any higher-res icons, as those would be nice for the 1080 UI.

---Alex

**Comment by kaileu** [comment]
The only possibility i see is to ship the logos with the addon instead  
downloading it.
This could be easy handled because they ship svg. But as far as i am  
reading Kodi isn't supporting svg so the cant't be downloaded and  
displayed. Or we upload the pictures on Github itself and download it  
from there.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment]
@kaileu Yeah, I'd like to avoid shipping our own copies of those logos, lest we encounter trademark/copyright stuff. It's much safer to use what each user downloads from the Game pass servers.

**Comment by kaileu** [comment]
If we found a way to render svg we could use this.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment]
@kaileu That's a png, why would we need to render SVG?

As for the original clients, they're made by the NFL, so they can redistribute their IP. We don't have a license from them to distribute their IP, hence why we can't ship copies.

---Alex

**Comment by kaileu** [comment]
Ok There are few thinks ;-) I know what you mean i wanted to say that the original Clients didn't download these images ;-)

2. The 144x96 Resolution in png is at the moment the only one we could use as a improvement.
3. If we could render svg we could use this one http://i.nflcdn.com/static/site/7.4/img/logos/svg/teams-matte/ATL.svg and we could use every Resolution we want if 4k or full-hd.

Sorry for the confusion ;-)

**Comment by Ghoschdi** [comment]
I think the challenge could be the workload to render all the SVGs during start of the addon.
There is (or was) a python module of librsvg called **pyrsvg** and i found this re XMBC: http://trac.kodi.tv/ticket/4332 - unfortunately this was never implemented?

**Comment by Alexqw** [comment]
@kaileu Ahh, ok. I understand what you're saying now. :-)

If there's an svg2png script we can use that'd be great. Sounds like @Ghoschdi looked around and didn't find anything though :-/

It's not a big deal. Obviously the UI is fine as it is. Just hoping and dreaming. ;-)

---Alex

**Comment by Ghoschdi** [comment]
Having a second thought and before opening another feature request, how about using the CairoSVG python module? http://cairosvg.org/documentation/

**Comment by Alexqw** [comment]
@Ghoschdi Unfortunately, this won't work for a couple of reasons, but the most glaring is that it requires Python 3 and needs to be compiled (and binary addons are not an option until Krypton comes out). Image conversion just tends to be a pretty involved process. :-/

---Alex

**Comment by Ghoschdi** [comment]
Ah, you are right. I did not read carefully and got past the "you need to have the binary" like imagemagick...

Well, so the only option (if Kodi will not implement it itself) is to use a cloud based service. But most of the good ones only have very limited free of charge APIs, like https://cloudconvert.com/api :(

**Comment by Alexqw** [comment]
@Ghoschdi And using an external service is technically redistributing, which is what we're trying to avoid in the first place. So, best course of action seems to be to look/hope for larger images somewhere on the Game Pass servers.

**Comment by Ghoschdi** [comment]
@Alexqw: Got it. Without looking at the code myself, i have one question i hope you can answer easily: Do the arrays home_team/away_team provide an index which returns the team name similar to the ID, e.g. home_team['id'] = SEA home_team['name'] =seahawks? If so, the solution is to drag the large.pngs from the official NFL club sites:

http://prod.static.seahawks.clubs.nfl.com/nfl-assets/img/gbl-ico-team/SEA/logos/home/large.png
http://prod.static.texans.clubs.nfl.com/nfl-assets/img/gbl-ico-team/HOU/logos/home/large.png
http://prod.static.patriots.clubs.nfl.com/nfl-assets/img/gbl-ico-team/NE/logos/home/large.png
etc.

**Comment by Ghoschdi** [comment]
```
"http://prod.static.{0}.clubs.nfl.com/nfl-assets/img/gbl-ico-team/{1}/logos/home/large.png".format(away_team['name'],away_team['id']))
listitem.setProperty('home_thumb', "http://prod.static.{0}.clubs.nfl.com/nfl-assets/img/gbl-ico-team/{1}/logos/home/large.png".format(home_team['name'],home_team['id']))
```
Which includes the "fix" for the outdated % format string, which will also work for phyton 3.x.  But since the GUI does not really offer more space than the used 82x53px, the question is if this makes any sense?

**Comment by Alexqw** [comment]
@Ghoschdi 1200x1200 seems a bit... large for our purposes. ;-)

We do have a bit more room than 82x53 (the skin was originally designed for 720, which is why there's a bit more room for images), but you're right, not a ton.

---Alex

**Pull request closed without merging**
