### PR TITLE
Changed login to use username

### PR DESCRIPTION
**Pull request by DMaiorino**
Love this addon! I can't wait to start using it next season.

When testing last night, I found that it asked for the email address, but I needed to use my username to login.

### CODE REVIEW

**Comment by Alexqw** [comment]
@DMaiorino Thanks for the bug report/PR. However, I can't reproduce your problem. Logging in with the email address works just fine for me.

If the problem is reproduceable for you, can you attach a debug log, so I/we can take a look to make sure nothing else funky is going on?

Thanks. :-)

---Alex

**Comment by DMaiorino** [comment]
Sorry, looks like I was using an old email for my account, so I can confirm that the email works as well :) I was comparing with my other apps for NFLPass, and they requested username so I was thinking we could follow suit with the same login naming. But either way seems to work, so I can drop the request if email is preferred.

Thanks for the quick feedback!

**Comment by Alexqw** [comment]
> Sorry, looks like I was using an old email for my account, so I can confirm that the email works as well :)

Haha. No worries. ;-)

> I was comparing with my other apps for NFLPass, and they requested username so I was thinking we could follow suit with the same login naming.

I have no problem with re-labeling the field to something akin to
"Username/Email". The settings IDs should remain untouched, though.

Update the PR to only update the labels, and I'd be happy to merge it. :-)

---Alex

**Comment by DMaiorino** [comment]
Awesome, thanks for the feedback! I have made the change with the labels. I do not speak German/Dutch, so please let me know if my Google translate is incorrect ;)

**Comment by Alexqw** [comment]
Merged; sorry for the long delay.

Thanks for the patch!

---Alex

**Pull request closed without merging**
