### PR TITLE
Skin update

### PR DESCRIPTION
**Pull request by eriksoderblom**
I've added a 1080 version of the skin, and updated the images for the higher resolution.
Also made some small changes for the 720 version.

I have not tested coaches film in 1080, because it does not seem to be working anymore.
So that might need some adjustment later.

### CODE REVIEW

**Comment by Alexqw** [comment]
@eriksoderblom Thanks for the update/upgrade. I tested it out and it looks great. :-)

It's interesting that you're having problems with Coaches Film, since it works just fine for me (on Helix). There's some layout issues (due to the res bump) but other than that it's just fine.

Would you like me to go ahead and merge this, or would you like a chance to see if you can resolve your coaches film problems so you can update it in this PR as well?

---Alex

**Comment by eriksoderblom** [comment]
Made some adjustments to coaches film, it should be fine to merge now.

But something is up with coaches film in Isengard, I had to do the testing in Helix.
I could provide a log later if it is needed.

**Comment by BaumSchorle** [comment]
@eriksoderblom I will check Coaches Film tonight or during weekend, when I have some time.

Just to mention: we could get rid of this whole GameRewind stuff as NFL doesn't offer this product anymore. They merged it to GamePass.

**Comment by Alexqw** [comment]
@eriksoderblom Merged. Thanks for the fixes. I made some tweaks to the game text; it looks good on my screen, but if I missed something and breaks horribly somewhere, feel free to dispose of it.

By the way, any reason for 1080i instead of 1080p?

@BaumSchorle I'll open a ticket for the coaches film stuff. And I agree, the GameRewind assets (and code and settings, once we figure out how the new service works) can all be removed. Plus we need a new icon.

**Comment by eriksoderblom** [comment]
@Alexqw Your changes look good.

1080i is the folder where kodi looks for the skin, 1080p might work too, I didn't try it.
http://kodi.wiki/view/Skin_development_introduction#Anatomy_of_a_Skin

**Comment by Alexqw** [comment]
@eriksoderblom Ahh, ok. I figured that was the res of the skin, but if it's only a naming convention, then I'm fine with that. But if it is resolution based, then I think it makes most sense to only use progressive rather than interlaced.

---Alex

**Pull request closed without merging**
