### PR TITLE
Font fix for non Confluence skins

### PR DESCRIPTION
**Pull request by BaumSchorle**
This should fix isssue #85 

It is still just a workaround.

### CODE REVIEW

**Comment by Alexqw** [comment]
@BaumSchorle I tested this with Amber on Kodi 14.2, and I don't see an improvement. :-/

I still hesitate about using this approach; I just really wish/hope the Kodi devs will give us a real solution in Kodi 16. But I'm afraid that's unlikely to happen, and this hack is the only solution.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw Strange.... works perfectly on my Installation on various Skins.... :-/

Maybe we get a real solution some time, but until then I think this is the only solution.

**Comment by Alexqw** [comment]
@BaumSchorle Hmm... I'll look at it more. Maybe I'm missing something.

I agree about this being the solution for now. I'm just cranky that the kodi guys aren't taking this issue seriously. :-/

---Alex

**Comment by Alexqw** [comment]
@BaumSchorle So the patch does help, but the drop-shadow is still quite off. :-/ Any thoughts? I've attached a screenshot.

---Alex

screenshot from 2015-08-10 14-48-31

**Comment by BaumSchorle** [comment]
uff.... this looks strange! Maybe we need to provide a font that does support shadows!?

The hack works pretty simple:

1.) copy a font file into the Skin folder
2.) add the new "gamepass fonts" to the fonts.xml file of the skin
3.) refresh skin

Maybe we need to use a different font file!?

**Comment by Alexqw** [comment]
@BaumSchorle I thought the drop-shadow was an intentional effect, and just assumed it was off by a few pixels. Though it could just be a font glitch.

BTW, we should make sure whatever font we use, that it's open source (Google Fonts has tons) and we add the appropriate info to the License file.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw I just used the standard Confluence font for testing purposes, but you are definitely right, we should use an open source font.

Strange is that we don't even define a drop shadow, so it may be inherited from the skin, maybe there is some kind of default(??).

**Comment by Alexqw** [comment]
So, I decided to merge this. It does fix the font sizing/spacing issue, which is the biggest problem. But it does seem some skins have a font shadow crudely implemented and it can make some skins look... unfortunate.

However, it's worth noting that some Kodi users will be prompted with a "This addon needs to install some extra resources", which is due to the hack-around nature of this approach. Nothing janky is going on (in an ethical sense).

Also, the issue tracker for spotimc (which uses skinutils, and is from the same dev as skinutils) does have quite a few bugs with crashes, etc. This could be unrelated, but it's worth keeping an eye on. This approach /may/ be more trouble that it's worth from a stability standpoint.

@BaumSchorle Thanks for taking the time to push this issue forward. It does look quite a bit better. :-)

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw I will try to set up a test environment with a skin which uses drop shadows and will try to fix this. I hope it will be easy with adding the 'shadow-tag' to our skin-xml files.

**Comment by Alexqw** [comment]
That'd be great. I noticed problems in Amber and Transparency. Neon worked well, and Confluence (obviously) was perfect. Though Transparency has so many issues, I'm not sure if it's worth even looking at.

All were tested under Helix (still waiting for Isengard to hit Debian sid...).

I hope all is well with you in Österreich. :-)

---Alex

**Comment by Alexqw** [comment]
Just as FYI: https://github.com/mazkolain/xbmc-skinutils/issues/1#issuecomment-131354958

**Pull request closed without merging**
