### PR TITLE
Adding Season 2016

### PR DESCRIPTION
**Pull request by kaileu**
Url changed:
http://smb.cdnak.neulion.com/fs/nfl/nfl/mobile/weeks_v2.xml to
http://neulionms-a.akamaihd.net/fs/nfl/nfl/mobile/weeks_v2.xml

### CODE REVIEW

**Comment by BaumSchorle** [comment]
@kaileu Thanks for updating! I merged it to master!

**Comment by Alexqw** [comment]
@kaileu Thanks for the patch. Looks like they're starting to switch over to akamai, so we should keep an eye out for more URL changes in the future.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw While working on parsing shows dynamically I stumbled across some urls they are providing in their xml return.
Maybe we can find all of these urls somewhere in the return to have it more dynamically.

**Comment by Alexqw** [comment]
@BaumSchorle Nice. :-)

**Comment by kaileu** [comment]
@Baumschorle Which urls did you not found?

**Comment by BaumSchorle** [comment]
@kaileu I haven't checked, I just had the idea when I saw it yesterday night. I will check today and hopefully we have all the urls we need

**Comment by BaumSchorle** [comment]
Bad news, I couldn't find the new url in the return from the server.
@kaileu how did you find the new url?

**Comment by kaileu** [comment]
I dumped the traffic ;-)

But i think the end ist hardcoded (mobile/weeks_v2.xml)
The Url itself is in simpleconsole locEDL

**Pull request merged**
