### PR TITLE
16.0 Jarvis compatibility

### PR DESCRIPTION
**Pull request by dahlSTROM**
Minimum GUI version was bumped up to 5.10.0 on Jarvis. You should probably push out a new version to the Kodi repository. :)

This solves #222.

### CODE REVIEW

**Comment by Alexqw** [comment]
Thanks for the fix @dahlSTROM Though, if I'm correct, bumping our requirement for xbmc.gui to 5.10.0 will make it uninstallable on Isengard.

The easy fix is to just drop the line, but we do depend on certain GUI features, which is why the dependency was bumped before (we're no longer compatible with Helix).

Does anyone know if the Kodi guys publish data about the percentage of users on each version of Kodi? If the uptake is fast to a new version, I'm willing to bump this and leave Isengard behind for new features/fixes. Otherwise, I think dropping the line is the only real option.

Thoughts?

---Alex
---Alex

**Comment by kaileu** [comment]
As long as there isn't a stable release i wouldn't change anything.
Vice versa as soon a new stable release is bump i would upgrade.

Mit freundlichen Grüßen
Kai Leutner

**Comment by dahlSTROM** [comment]
Oh, my bad. I had no idea this would break compatibility with Isengard. 

In my option, dropping the line seems to be the best option for now. It's the only way to support both older and newer versions.

**Comment by Alexqw** [comment]
So, I decided to make the change, apply this patch, and create a branch for isengard. I am submitting a request to the Kodi devs to update the addon for Helix-Jarvis.

**Pull request closed without merging**
