### PR TITLE
Adding dynamic Url parsing

### PR DESCRIPTION
**Pull request by kaileu**
New PR with a clean Push :'D

### CODE REVIEW

**Comment by Alexqw** [comment]
@kaileu Thanks for the squashed PR. :-)

I have a few comments:

Please do not import xbmc in pigskin.py; it should be able to run completely independent of Kodi. It seems you're only using it for logging, and you can just use self.log in those instances.

What does the EDL in locEDLBaseUrl  stand for? A more intuitively named variable would be better.

So, I see that you're putting this in __init__. I'm not so sure it belongs there, as authentication has not happened yet. It's likely working for you due to cached credentials, but on a fresh run, I'd expect this to fail.

Perhaps this is best done as part of the login process, setting up these additional URLs.

The main issues are importing xbmc and making sure a fresh login works. If those are taken care of, I'll merge and it can be iterated upon. :-)

---Alex

**Comment by kaileu** [comment]
[simpleconsole_output.xml.txt](https://github.com/Alexqw/xbmc-gamepass/files/381482/simpleconsole_output.xml.txt)

Reply:
1.
What does the EDL in locEDLBaseUrl stand for?
I have no Idea :'D its the Value in the XML file and because i am using only the base Url i call it that way so ist possible to debug if the value changed. I added the corresponding xml file for later lookup.
2.
So, I see that you're putting this in init. I'm not so sure it belongs there, as authentication has not happened yet. It's likely working for you due to cached credentials, but on a fresh run, I'd expect this to fail.

No for this request no authentication is necessary. The Information are there no matter if you are logged in or not.



i had a few git Problems XD sorry for the multiple updates

**Comment by Alexqw** [comment]
@kaileu Awesome. Thanks for working on this!

Merging...

---Alex

**Comment by Alexqw** [comment]
@kaileu I'm writing up the changelog right now for this feature, and I was thinking... this change might actually be /really/ nice. Right now, with the hard coding, everyone has been using the DNS names, which has been working. But maybe GamePass returns different servers for different regions. I'm curious if (when the season comes) if this will affect Domestic users or if we'll get fewer buffering complaints.

---Alex

**Comment by kaileu** [comment]
@Alexqw  Thats a good Point. I didn't think about it but youre right maybe this can influence other region but i hope for good.

**Pull request closed without merging**
