### PR TITLE
Detect subscription type in pigskin

### PR DESCRIPTION
**Pull request by emilsvennesson**
There's really no need to let the user select subscription type as the info is available in the simpleconsole response.

### CODE REVIEW

**Comment by Alexqw** [comment]
@emilsvennesson After that recent issue, I had this idea too. You beat me to it. ;-)

This patch is /almost/ complete. Take a look in default.py for the variable 'subscription'. It is used in a few places to control access and change a logo in the GUI. I recommend adding a function in pigskin.py named 'get_subscription_type()' (or something like that) that checks if self.subscription is set. If so, it returns it, otherwise it gets it from a simpleconsole request. Then call it in default.py, make sure pigskin.py looks sane, etc.

---Alex

**Comment by emilsvennesson** [comment]
@Alexqw Great minds think alike, huh? :smirk:

Whoops, I didn't even notice the subscription variable in default.py. PR has been updated.

**Comment by emilsvennesson** [comment]
Alright, please don't review this yet.. I did some mistakes, hah.

**Comment by emilsvennesson** [comment]
@Alexqw This should (hopefully) be good to go now...

**Comment by Alexqw** [comment]
@emilsvennesson Merged

So... turns out I was a bit of an idiot and the gpr.get_subscription_type function isn't needed, since default.py can access gpr.subscription directly. Doing too many things at once today. :-)

Anyway, I cleaned that up and squashed it into your patch.

Everything /should/ be good. Though I admit I was a bit hurried, so let me know if I screwed anything up. ;-)

---Alex

**Comment by emilsvennesson** [comment]
@Alexqw Your cleanup looks just like my original PR. :) That's what I thought as well, but I got confused by your confusion. :relieved:

**Comment by Alexqw** [comment]
@emilsvennesson Yeah... my bad. Though, /one/ thing is different (I think) from the original. In default.py it's gpr.subscription now rather than subscription.

Thankfully it's the weekend. Time for much needed beer. :-)

---Alex

**Pull request closed without merging**
