### PR TITLE
Remove rewind, add international/domestic logos

### PR DESCRIPTION
**Pull request by eriksoderblom**
Changed the check for Gamepass in default.py to check for domestic.
I don't know where you look if domestic or international, but maybe it could be done using the same variables as the Gamepass check.

### CODE REVIEW

**Comment by Alexqw** [comment]
@eriksoderblom Nice. I especially like the new logos.

Did you omit the 720p skin intentionally?

---Alex

**Comment by eriksoderblom** [comment]
I didn't omit it intentionally, I just forgot about it... I'll fix it right now

**Comment by eriksoderblom** [comment]
@Alexqw 720p skin should be alright now.

**Comment by Alexqw** [comment]
Talk about fast turnaround time. Thanks again @eriksoderblom  :-D

---Alex

**Comment by frostyon420** [comment]
so glad to have GP again :) thanks for the work guys

**Pull request closed without merging**
