### PR TITLE
Resolution Change

### PR DESCRIPTION
**Pull request by kaileu**
Its not the best one but better as the old ones XD

### CODE REVIEW

**Comment by Alexqw** [comment]
@kaileu Oddly, I don't see much of a difference... and they are downloading...

Am I missing something obvious?

---Alex

**Comment by kaileu** [comment]
The Resolution we are currently using is 80x53 these one are 144x96 which means they are a bit sharper.
So these images are slithly bettern than the old one if you take a look on the image itself you see the diffrence. 
http://i.nflcdn.com/static/site/7.4/img/logos/teams-matte-144x96/SEA.png
http://i.nflcdn.com/static/site/7.4/img/logos/teams-matte-80x53/SEA.png

What did you mean with "and they are downloading" i didn't get that point.

**Comment by Alexqw** [comment]
@kaileu Ahh, I expected the visual size to change as well. That's why I was confused.

The "and they are downloading" was me stating that I definitely was getting the new images (rather than having the old ones cached).

Things make sense now. Will merge.

---Alex

**Comment by Alexqw** [comment]
Thanks for the patch. :-)

**Pull request closed without merging**
